name: ghcr.io CI/CD

on:
  push:
    tags:
      - 'v*'
    
env:
  REGISTRY: "ghcr.io"
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_SECRET: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_NAME: ${{ github.repository }}

permissions:
  contents: read
  packages: write
   
jobs:
    build_and_publish:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            include:
              - docker_file: Dockerfile
              - docker_file: Dockerfile.cuda
                tag-suffix: -cuda
        steps:
            - uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Meta
              id: meta
              uses: docker/metadata-action@v5
              with:
                images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
                flavor: |
                  latest=true
                  suffix=-${{ matrix.tag-suffix }}
                  onlatest=true

            - uses: docker/login-action@v3
              with:
                registry: ${{ env.REGISTRY }}
                username: ${{ env.REGISTRY_USER }}
                password: ${{ env.REGISTRY_SECRET }}

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                context: .
                push: ${{ github.event_name != 'pull_request' }}
                tags: ${{ steps.meta.outputs.tags }}
                platforms: linux/amd64,linux/arm64